# Generated by Django 6.0.6 on 2026-07-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'シフト', 'verbose_name_plural': 'シフト'},
        ),
        migrations.AlterModelOptions(
            name='shiftfile',
            options={'verbose_name': 'シフトファイル', 'verbose_name_plural': 'シフトファイル'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '職員', 'verbose_name_plural': '職員'},
        ),
        migrations.AddField(
            model_name='shiftfile',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
