# Generated by Django 6.0.6 on 2026-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_app', '0002_alter_shift_options_alter_shiftfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shiftfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='meeting',
        ),
        migrations.AddField(
            model_name='shift',
            name='weekday',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='laundry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shiftfile',
            name='title',
            field=models.CharField(default='勤務表', max_length=100),
            preserve_default=False,
        ),
    ]
