# Generated by Django 6.0.6 on 2026-07-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_app', '0003_alter_shift_options_alter_shiftfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
